### ISSUE TITLE
请问程序在哪里下载呢

### ISSUE THREAD

**Issue by superjock1988** [peiqiF4ck/WebFrameworkTools-5.1-main#1]

**Comment by peiqiF4ck** [comment]
由于考虑到大环境。目前没有开放下载。感谢对软件的支持。后续可能会开放下载敬请期待。可能年底或者是某个时间开放下载。到时候会在release中放置下载链接。详情关注频道。后续软件内部化防止有问题

**Comment by peiqiF4ck** [comment]
程序已经开放下载在 release那里。感谢关注
