### ISSUE TITLE
dll生成器UserDllpluginExpGenerate Exp自动生成器 在https://github.com/peiqiF4ck/ToolsUserDllplugin没找到exe生成工具

### ISSUE THREAD

**Issue by 0day4day** [peiqiF4ck/WebFrameworkTools-5.1-main#3]
师傅你好
dll生成器UserDllpluginExpGenerate Exp自动生成器 在https://github.com/peiqiF4ck/ToolsUserDllplugin没找到exe生成工具

如图，没看到下载的
![image](https://github.com/user-attachments/assets/fda0d679-16d7-4b70-bf8c-8482272121a8)

好像过期了

**Comment by 0day4day** [comment]
没事了在群聊在找到了师傅

**Comment by peiqiF4ck** [comment]
去频道下载如果过期。修改本地时间。另外今年hw完毕后重新准备放出10万条url的届时将更新 图形化exp生成工具请知晓。另外这个工具在 发布的 V5.3beta版本里面有请在博客或者频道下载。测试未过期。
![4`1CO)YP1)7 RZ`A4DJUV 1](https://github.com/user-attachments/assets/37b6a850-d46d-44d9-83df-2b1e97bad6a8)
